title: "Chirag's Cybersecurity Vault"
description: "Notes on Cybersecurity, Learning Journey, and Projects"
theme: jekyll-theme-minimal  # Base theme, though it won't affect custom layouts
markdown: kramdown

# Include custom CSS and layouts
include:
  - styles.css
  - _layouts/default.html

exclude:
README.md
